### ISSUE TITLE
VS Hangs when deploying to Meadow

### ISSUE THREAD

**Issue by johnkattenhorn** [WildernessLabs/VS_Win_Meadow_Extension#130]
**Describe the bug**
If you create a new Meadow Project and attempt to deploy and debug VS 2022 hangs and program does not run on the Meadow.

**To Reproduce**

1. Create a new Meadow app using `dotnet new Meadow --output c:\code\scratch\meadowapp
2. Open Project in VS 2022
3. Open Meadow Device Toolbar and Select Meadow Device
4. Set Breakpoint line 18 `Resolver.Log.Info("Initialize...");
5. Build and Deploy App to Meadow
6. Output stops at  Download of 'wifi.config.yaml' success (checksums calculated:0xE71DFFE4, expected:0xE71DFFE4)
 Mono is disabled
 Mono has been enabled - restarting Meadow
 Meadow successfully started MONO
 Mono is enabled
 Meadow successfully started MONO
7. Debugger starts but breakpoint not hit
8. Click Stop Debugging causes VS 2022 to crash after a while
9. Meadow appears not be running code

**Expected behavior**
1. Create a new Meadow app using `dotnet new Meadow --output c:\code\scratch\meadowapp
2. Open Project in VS 2022
3. Open Meadow Device Toolbar and Select Meadow Device
4. Set Breakpoint line 18 `Resolver.Log.Info("Initialize...");
5. Build and Deploy App to Meadow
6. Debugger is started, code starts to run outputting Logs and Breakpoint is hit.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Build 22621.1848
 - Browser Edge
 - Version 114.0.1823.51 (Official Build) (64-bit)

**Additional context**
I suspect some breaking change in VS 2022 debugger - it would be useful to know which version is the last which is working for everyone.

**Comment by CartBlanche** [comment]
@johnkattenhorn thanks for raising the issue. We're testing a 1.0.4.x build internally, which we hope fixes sone recent issues. 
Can you please confirm which version of Meadow.CLI you are using as well as which version of the VS extensions?

**Comment by johnkattenhorn** [comment]
@CartBlanche - if I type `meadow --version` is returns `v1.0.2.2`, I can't figure out how to get the version numbers from templates - I've tried this `dotnet new list Meadow --columns-all` but it doesn't return a version that I can see.

**Comment by CartBlanche** [comment]
@johnkattenhorn please see this ports on #support  https://wildernesslabspublic.slack.com/archives/CQWD660E8/p1687888809166749

The versions of VS extensions would be found in the IDE itself. Under `Visual Studio->Extensions` on Mac or `Extensions->Manage Extensions` on Windows and just under `Extensions` in VSCode.

Let me know if 1.0.4 helps.

**Comment by johnkattenhorn** [comment]
I think we can close this one now @CartBlanche
