### ISSUE TITLE
Out of the box MeadowApp.cs does not compile

### ISSUE THREAD

**Issue by devingoble** [WildernessLabs/VS_Win_Meadow_Extension#14]
**Describe the bug**
With the most recent version of the Visual Studio extension (0.10.1), the Meadow Application template comes with code that does not appear to compile by default.

**To Reproduce**
1. Create a new Meadow Application project
2. Open MeadowApp.cs
3. Observe an error on line 32

**Expected behavior**
The template should at least compile with no additional changes needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/2547980/90299879-a7a96a00-de4c-11ea-8ee9-a9313c0dac16.png)

**Additional context**
I was able to fix the issue by looking at some of the samples in the Meadow.Foundation repo.

Adding `using static Meadow.Peripherals.Leds.IRgbLed;` and changing line 32 to `CommonType.CommonAnode);` seems to work fine.

**Comment by devingoble** [comment]
I'd be happy to submit a PR that I believe resolves the issue, but the extension solution doesn't appear to build either.

**Comment by adrianstevens** [comment]
This is fixed - closing issue
