### ISSUE TITLE
Deploy fails on first attempt

### ISSUE THREAD

**Issue by brucecrombie** [WildernessLabs/VS_Win_Meadow_Extension#16]
Extension version 0,11,1
Sometimes when attempting to deploy an app over an existing running app the deploy fails on the first attempt with a "The port is closed" error.
This behavior only started manifesting itself with larger multithread apps running.
After the failed deploy the meadow is left in a halted state and the previous app will no longer reboot with a reset.
A second attempt to deploy always works.

2>------ Deploy started: Project: MeadowTest400, Configuration: Debug Any CPU ------
2>[10/01/20 5:31:22 AM]     Deploying to Meadow on COM6...
2>[10/01/20 5:31:22 AM]     Initializing Meadow                                                                                                      (00:00:00.0002871 since last.)
2>The port is closed.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by adrianstevens** [comment]
The should be fixed in the latest version - closing issue
