### ISSUE TITLE
High CPU load during deployment with 0.6.0

### ISSUE THREAD

**Issue by marcinsmialek** [WildernessLabs/VS_Win_Meadow_Extension#2]
When deploying a simple variation of Hello Meadow, it writes all the dlls even after minimal changes.
It takes quite a lot of time, and Visual Studio consumes around **30%** CPU during this process (6-cores + HT i7 8700K).

----
Subsequent reflashing seems to help.

**Comment by adrianstevens** [comment]
This should be fixed in the current release - closing issue
