### ISSUE TITLE
Extension gives no feedback when first setting up

### ISSUE THREAD

**Issue by frankhaugen** [WildernessLabs/VS_Win_Meadow_Extension#6]
The extension gives absolutely no feedback. I click the "Download Meadow OS"-button and literally nothing happens. I don't get any error messages or anything.

The Troubleshooter button works, but there's no information about troubleshooting the actual extension.

There should be a clear message that something is happening, or that something isn't happening because something is wrong

**Comment by frankhaugen** [comment]
Turns out that the feedback is in the output window, (the use of a button should highlight this, as I had PMC in focus, and nothing indicated that the output was showing something.

I figured this out by looking at the source code

**Comment by adrianstevens** [comment]
The extension is no longer downloading the OS - guidance is to use the Meadow CLI - closing issue

**Comment by frankhaugen** [comment]
> The extension is no longer downloading the OS - guidance is to use the Meadow CLI - closing issue

It's almost a year ago and there's been no response...
