### ISSUE TITLE
Adding first application took 43 minutes

### ISSUE THREAD

**Issue by frankhaugen** [WildernessLabs/VS_Win_Meadow_Extension#7]
When setting up my first project I had to wait 45 minutes from I pressed F5 to it finished, some of the DLLs had such a long time in between them, that I worried it was hung-up.

This should be improved as it's just compiling DLLs and copying them to the device

**Comment by frankhaugen** [comment]
Doing a single line change to the code, (I am using the template project), took just as long to add to the board

**Comment by adrianstevens** [comment]
fixed - closing
