### ISSUE TITLE
Blue Screen in VM Player 15 using Meadows explorer in VSTUDIO 2019 preview

### ISSUE THREAD

**Issue by janflikweert** [WildernessLabs/VS_Win_Meadow_Extension#9]
Issue VMPlayer15 ended in a blue screen 

Timeframe Februari 2020 
Installed as (only) application in a windows 10  virtual system in VM Player 15 was VSSTUDIO 2019 Community preview updated to the latest version. (Windows also the latest update) 

I just received the meadow board and followed the getting started guide. 

Assemble your Meadow board (Completed) 

Deploy Meadow OS to your Board 

In point 2 I followed the installation process to the letter. 
a/installation via Visual Studio Extension (Windows) This is recommended for Windows users. 
 

My starting point was I had Visual Studio installed and almost all frameworks installed. I used the system for training purposes and learning about new language additions. I thought I was in good shape because no prerequisites where asked for by Wilderness labs If you follow the installation process to the letter. 
So: 

In Visual Studio, go to Extensions > Manage Extensions. 

Click Online and search for Meadow. 

Install VS Tools for Meadow (version 0.6.0 or later), shut down all instances of Visual Studio, and restart. 

Open Visual Studio 2019 and select Continue without code. 

Open Meadow Device Explorer: View > Other Windows > Meadow (or Ctrl+Shift+M). 
Meadow Device Explorer 

So far so good everything was fine. Now in the next steps it goes wrong. 
Meadow device Explorer is what you could not call a communicative program so following the steps I ended up with a blue screen! (After minutes of waiting) 
 

Click Download MeadowOS. 

Connect your Meadow device in bootloader mode by connecting your device while holding down the BOOT button. 

Click Flash Device. This will take a couple minutes to complete. 

Choose the correct port in Select Target Device Port dropdown. Hint: open Device 
 Manager and expand Ports (COM & LPT), the correct Meadow device COM port is USB Serial Device. 

Please change the getting started guide. 

Please move the following section  

Windows 

You’ll need to ensure the .NET Framework 4.7.2 SDK and targeting pack are installed. To verify, run the Visual Studio Installer and click More > Modify. Under Individual Components, check .NET Framework 4.7.2 SDK and .NET Framework 4.7.2 targeting pack and install. 

From “Hello, Meadow” to the deployment section. 

If you do that and everyone follows step 1,2,3 then everything is fine. It could save  a lot of calls. 

(And at least this case of Blue Screen is VM Player 15 is solved there are other issues.  It caused me to abandon VM Player 15 at this moment)

**Comment by adrianstevens** [comment]
this should be fixed with the update to .NET Standard - closing issue
